package:
  name: "h5sparse-tensor"
  version: { { GIT_DESCRIBE_TAG.lstrip('v') } }

source:
  git_url: ../..

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - h5py
    - python
    - six
    - pip
  run:
    - h5py
    - numpy
    - python
    - scipy
    - six

test:
  imports:
    - h5sparse
  source_files:
    - tests/tests.py
  requires:
    - pytest
  commands:
    - pytest -v tests/tests.py

about:
  home: "https://github.com/tvandera/h5sparse"
  license: MIT
  license_family: MIT
  license_file:
  summary: "Scipy sparse matrix in HDF5."
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - tvandera
